version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: technical-test-ronny:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true