CREATE TABLE IF NOT EXISTS ASSETS
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename     VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    url          VARCHAR(500),
    size         BIGINT       NOT NULL,
    status       VARCHAR(50)  NOT NULL,
    upload_date  TIMESTAMP NOT NULL
);